home/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from . import views

app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home , name='home'),

    # modalities

    path('ecg/', views.ecg , name='ecg'),
    path('eda/', views.eda , name='eda'),
    path('emg/', views.emg , name='emg'),
    path('resp/', views.resp , name='resp'),
    path('temp/', views.temp , name='temp'),

    # about section

    path('about/', views.about , name='about')

]

stress_detector/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .classifier import nn_predictions


def home(request):
    return render(request, 'home/home.html')


def about(request):
    return render(request, 'home/about.html')


# modalities

def eda(request):
    if request.method == 'POST':
        path = request.FILES['myfile']  # this is my file
        ac_class, confidence_score, secs = nn_predictions(path, 'EDA')

        print(path)

        print('here .....................')

        print(ac_class, confidence_score)

        return render(request, 'home/eda.html', {"class": ac_class, "score": confidence_score, "path": path, "time": secs})

    else:
        return render(request, 'home/eda.html')


def emg(request):

    if request.method == 'POST':
        path = request.FILES['myfile']  # this is my file
        ac_class, confidence_score, secs = nn_predictions(path, 'EMG')

        print(path)

        print('here .....................')

        print(ac_class, confidence_score)

        return render(request, 'home/emg.html', {"class": ac_class, "score": confidence_score, "path": path, "time": secs})

    else:
        return render(request, 'home/emg.html')


def ecg(request):
    if request.method == 'POST':
        path = request.FILES['myfile']  # this is my file
        ac_class, confidence_score, secs = nn_predictions(path, 'ECG')

        print(path)

        print('here .....................')

        print(ac_class, confidence_score)

        return render(request, 'home/ecg.html', {"class": ac_class, "score": confidence_score, "path": path,  "time": secs})

    else:
        return render(request, 'home/ecg.html')


def resp(request):
    if request.method == 'POST':
        path = request.FILES['myfile']  # this is my file
        ac_class, confidence_score, secs = nn_predictions(path, 'Resp')

        print(path)

        print('here .....................')

        print(ac_class, confidence_score)

        return render(request, 'home/resp.html', {"class": ac_class, "score": confidence_score, "path": path,  "time": secs})

    else:
        return render(request, 'home/resp.html')


def temp(request):
    if request.method == 'POST':
        path = request.FILES['myfile']  # this is my file
        ac_class, confidence_score, secs = nn_predictions(path, 'Temp')

        print(path)

        print('here .....................')

        print(ac_class, confidence_score)

        return render(request, 'home/temp.html', {"class": ac_class, "score": confidence_score, "path": path,  "time": secs})

    else:
        return render(request, 'home/temp.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" 
     crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'base.css' %}">

    <title>Stress Detector</title>


    <style>

*{
    box-sizing: border-box;
    padding: 0;
    margin: 0;
}


  
.jumbotron{ 
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    min-height: 90vh;
    
    
}

.box {
    padding: 0.5em;
    border-radius: 1em;
    max-width: 40vw;
    background: rgba(255, 255, 255, 0.2);
}

@media screen and (max-width: 480px) {
    .box{
        max-width: 90vw;
    }
    
}

.main-head{
    font-size: 3.5em;
    font-weight: bold;
    animation: mymove 4s infinite;
}

.sub-head {
    font-size: 2em;
    font-weight: lighter;

}

@keyframes mymove {
    50% {text-shadow: 4px 4px 4px white;}
  }

.big{

    min-height: 100vh;
    overflow-y: hidden;
    background-color: black;
    display: flex;
    flex-direction: column;
    
}

.btn {
    background-color: rgba(255, 255, 255, 0.1);
}


.box2 {
    padding: 2em;
    border-radius: 1em;
    max-width: 50vw;
    background: rgba(255, 255, 255, 0.1);
    color: white;
    font-weight: lighter;
    font-family: sans-serif;
    /* margin: 4em; */
    display: flex;
    flex-direction: column;
    justify-content: center;
    text-align: justify;
    

}

@media screen and (max-width: 480px) {
    .box2{
        max-width: 90vw;
    }
    
}

.about{
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    
}

.wrapper {
    display: flex;
    flex-direction: row-reverse;
    justify-content: center;
    flex-wrap: wrap;
    /* align-items: center; */
}

.holder{
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
}

.gyaan {
    display: flex;
    flex-direction: column;
}


    </style>


</head>
<body>

    <div class="big text-white">
        {% include 'partials/_navbar.html' %}

        <br>
        <br>
        <br>
        <br>
        

        {% block content %}
        
        {% endblock %}

    </div>


    
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" 
integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" 
crossorigin="anonymous"></script>

</html>

templates/home/about.html
{% extends 'base.html' %}{% load static %} 



{% block content %}
<div class="text-center about" style="background-color: rgba(0, 0, 0, 0.7); ">
    <div class="main-head">
        Neural Networks to Predict Stress.
    </div>

    <div class="sub-head">
        A Virtual Assitant
    </div>

    <br>
        
    <div class="wrapper">
    
        <div class="container box2">
            
            We live in a world where neural networks have achieved superhuman accuracy in almost every field. 
            It has brought a revolution and I believe it is just the start.

            <br>
            
            I have seen my friends and even me falling victim to stress, especially in an online world. 
            However, we usually dont have time to see a doc. Thus I designed a Neural Network to classify stress level of a person. 
            So, that if anything serious is brewing it can be nipped in the bud. 
            
            If successfull this will also make us aware of ourselves in a different way. Also we will get to know the very nature of stress.
            And probably come up with ways to prevent it.
            
            <br>

            If you liked this project consider staring or forking the <a href="https://github.com/sa-y-an/retro"> Repo</a>
            
            <br>

            <ul>
                <li>
                    DataSet - <a href="https://archive.ics.uci.edu/ml/datasets/WESAD+%28Wearable+Stress+and+Affect+Detection%29">
                        WESAD </a>
                </li>
                <li>
                    Tech Stack - Django + Tensorflow
                </li>
            </ul>

            For collaboration you can also visit me on the socials below. 
            Thanks for visiting and have a great day !


        </div>

        

        <div class="card bg-dark bg-gradient" style="width: 18rem;">
            <img src="https://avatars.githubusercontent.com/u/55195504?v=4" class="card-img-top" alt="Sayan Mondal">
            <div class="card-body">
              <h5 class="card-title">Sayan Mondal </h5>
              <p class="card-text">EE Undergrad <a href="http://nitdgp.ac.in/"> @NITDgp</a> 
                <br/> 
                AI Researcher. Developer</p>
              <a href="https://github.com/sa-y-an/" class="btn btn-secondary">Github</a>
              <a href="https://www.linkedin.com/in/sa-y-an/" class="btn btn-secondary">LinkedIn</a>
            </div>
        </div>

    </div>
        

</div>

{% endblock %}

templates/home/ecg.html
{% extends 'base.html' %}{% load static %} 


{% block content %}

<div class="container">

    <div class="main-head">
        ECG Data 
    </div>

    <br/>


    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
    
                <input type="file" name="myfile" class="btn btn-secondary" />
                <input type="submit" name="submit" value="Upload"  class="btn btn-secondary"/>
    
            </div>
        </form>

    </div>
    

    {% if score %}
        <div class="sub-head">
            Yout last Submission {{path }} was sucessfull
        </div>
           
       
        Here are the results. out of {{time}} of data, you were in  

        <table class="table table-dark table-striped">
            
            <thead>
                <tr>
                  <th scope="col">Excitation Type</th>
                  <th scope="col">Time (secs) </th>
                  
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">{{ class }}</th>
                  <td>{{ score }}</td>
                </tr>
                </tbody> 
        </table>


    {% else %}

        <p>
            Input the Files
        </p>

    {% endif %}

    <div class="container">
        
        <h4>
            Please read the "Measure Your Stress Level from this website" section in the home page before for clarity.
        </h4>

        <hr>


        <h3 id="instructions">
            Instructions To Use the site
        </h3>

        <p>
            To find out your stress level just input signal from anyone of the modalalities available on the navbar sampled at 700Hz 
            and has a minimum length of 1024 samples. And you will get your stress level.
            <br>
            <U>Conditions</U>
            <ul>
                <li>
                    upload a .csv file or .txt file consisting of your signal data.
                </li>
                <li>
                    If you are using .txt make sure the values are tab or space separated.
                </li>
                <li>
                    The signal should be sampled at 700Hz.
                </li>
            </ul>
        </p>


        <h5>
            Download Sample EDA Data
        </h5>
        <br>
        <a href="https://drive.google.com/file/d/17RzbfZ568KUnCKQM7yAxdhvp1sLDu41y/view?usp=sharing">
            <button class="btn btn-secondary">
                .CSV File
            </button>
        </a>
        
        <a href="https://drive.google.com/file/d/1DJVm5t89rlcBXcakce3r0Y5wP4KLsQzI/view?usp=sharing">
            <button class="btn btn-secondary">
                .TXT File
            </button>
        </a>
    </div>
    
</div>

{% endblock %}

templates/home/eda.html
{% extends 'base.html' %}{% load static %} 


{% block content %}

<div class="container">

    <div class="main-head">
        EDA Data 
    </div>

    <br/>


    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
    
                <input type="file" name="myfile" class="btn btn-secondary" />
                <input type="submit" name="submit" value="Upload"  class="btn btn-secondary"/>
    
            </div>
        </form>

    </div>
    

    {% if score %}
        <div class="sub-head">
            Yout last Submission {{path }} was sucessfull
        </div>
           
       
        Here are the results. out of {{time}} of data, you were in 

        <table class="table table-dark table-striped">
            
            <thead>
                <tr>
                  <th scope="col">Excitation Type</th>
                  <th scope="col">Time secs</th>
                  
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">{{ class }}</th>
                  <td>{{ score }}</td>
                </tr>
                </tbody> 
        </table>


    {% else %}

        <p>
            Input the Files
        </p>

    {% endif %}

    <div class="container">

        <h4>
            Please read the "Measure Your Stress Level from this website" section in the home page before for clarity.
        </h4>

        <hr>
        
        <h3 id="instructions">
            Instructions To Use the site
        </h3>

        <p>
            To find out your stress level just input signal from anyone of the modalalities available on the navbar sampled at 700Hz 
            and has a minimum length of 1024 samples. And you will get your stress level.
            <br>
            <U>Conditions</U>
            <ul>
                <li>
                    upload a .csv file or .txt file consisting of your signal data.
                </li>
                <li>
                    If you are using .txt make sure the values are tab or space separated.
                </li>
                <li>
                    The signal should be sampled at 700Hz.
                </li>
            </ul>
        </p>


        <h5>
            Download Sample EDA Data
        </h5>
        <br>
        <a href="https://drive.google.com/file/d/17RzbfZ568KUnCKQM7yAxdhvp1sLDu41y/view?usp=sharing">
            <button class="btn btn-secondary">
                .CSV File
            </button>
        </a>
        
        <a href="https://drive.google.com/file/d/1DJVm5t89rlcBXcakce3r0Y5wP4KLsQzI/view?usp=sharing">
            <button class="btn btn-secondary">
                .TXT File
            </button>
        </a>
    </div>
    
</div>

{% endblock %}

templates/home/emg.html
{% extends 'base.html' %}{% load static %} 


{% block content %}

<div class="container">

    <div class="main-head">
        EMG Data 
    </div>

    <br/>


    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
    
                <input type="file" name="myfile" class="btn btn-secondary" />
                <input type="submit" name="submit" value="Upload"  class="btn btn-secondary"/>
    
            </div>
        </form>

    </div>
    

    {% if score %}
        <div class="sub-head">
            Yout last Submission {{path }} was sucessfull
        </div>
           
       
        Here are the results,  out of {{time}} of data, you were in 


        <table class="table table-dark table-striped">
            
            <thead>
                <tr>
                  <th scope="col">Excitation Type</th>
                  <th scope="col">time secs </th>
                  
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">{{ class }}</th>
                  <td>{{ score }}</td>
                </tr>
                </tbody> 
        </table>


    {% else %}

        <p>
            Input the Files
        </p>

    {% endif %}

    <div class="container">

        <h4>
            Please read the "Measure Your Stress Level from this website" section in the home page before for clarity.
        </h4>

        <hr>


        <h3 id="instructions">
            Instructions To Use the site
        </h3>

        <p>
            To find out your stress level just input signal from anyone of the modalalities available on the navbar sampled at 700Hz 
            and has a minimum length of 1024 samples. And you will get your stress level.
            <br>
            <U>Conditions</U>
            <ul>
                <li>
                    upload a .csv file or .txt file consisting of your signal data.
                </li>
                <li>
                    If you are using .txt make sure the values are tab or space separated.
                </li>
                <li>
                    The signal should be sampled at 700Hz.
                </li>
            </ul>
        </p>


        <h5>
            Download Sample EDA Data
        </h5>
        <br>
        <a href="https://drive.google.com/file/d/17RzbfZ568KUnCKQM7yAxdhvp1sLDu41y/view?usp=sharing">
            <button class="btn btn-secondary">
                .CSV File
            </button>
        </a>
        
        <a href="https://drive.google.com/file/d/1DJVm5t89rlcBXcakce3r0Y5wP4KLsQzI/view?usp=sharing">
            <button class="btn btn-secondary">
                .TXT File
            </button>
        </a>
    </div>
    
</div>

{% endblock %}

templates/home/home.html
{% extends 'base.html' %}{% load static %} 


{% block content %}


    <div class="text-white">
        <div class="jumbotron" style="min-height: 95vh;">
            
                <div class="main-head text-center">
                    Know Your Stress Level 
                </div>
    
                <div class="sub-head">
                    Get help in advance 
                </div>
                <br>

    
                <div class="box text-center">
                    Do you know 77 percent of people experience stress that affects their physical health.
                    73 percent of people have stress that impacts their mental health.
                    If left unchecked this can have severe consequences.
                    <br>
                    Click the button below to know more.
                </div>

                <br/>

                <a href="#instructions">
                    <button class="btn btn-secondary">
                        Stress Check
                    </button>
                </a>
        </div>

        </div>
    </div>
    <!-- closes base big div tag -->


    <div id="instructions" class="container" style="min-height: 50vh;">
        <br>
        <br>

        <h1>
            Measure Your Stress Level from this website
        </h1>

        <p>
            
             
        </p>

        <p>
            <h3>
                How to Measure Stress From this site
            </h3>
        </p>


        <div class="holder">
            <div >
                <img src="https://github.com/sa-y-an/Qriosity/raw/master/explain.png" alt="explain" width="70%" align="center">
            </div>
            

            <div class="gyaan">
                <ul>
                    <li>
                        People now a day are quite stressed , but they rarely see a doctor to measure the stress level. 
                        
                    </li>
                    <li>
                        This site provides a way to <b> measure the stress level from the comfort of home </b> . 
                    </li>
                    <li>
                        Generally modern day <b>
                            smart watches
                        </b>  measures some form of physiological data from which the stress level can be calculated. 
                        like - ecg, emg, eda, respiration rate, body temperature, heart rate, pulse rate etc.
                    </li>
                    <li>
                        So I trained a Neural Network that can predict in which excitation state you are viz - 
                        <ol>
                            <li>
                                Neutral 
                            </li>
                            <li>
                                Stress
                            </li>
                            <li>
                                Amusement
                            </li>
                        </ol>
                    </li>
                </ul>
            </div>
        </div>
        <div>
            <h3>
                What Data to Enter ?
            </h3>

            <p>
                <ul>
                    <li>
                        Enter any one ecg, emg, eda, temperature, respiration data obtained from your smart watch
                        or any other device sampled at 700 Hz at their respective page ( see navbar ).
                    </li>
                    <li>
                        File Format - CSV or TXT 
                    </li>
                    <li>
                        The Model will give a prediction per 1024 samples ie 1.4 seconds, either for those 1.4 seconds your data is stressed, neutral or in amusement.  
                    </li>
                    <li>
                        In the end we output the most prevalent state, with the amount of seconds it was prevalent.

                    </li>

                    <li>
                        Sample Data Can be found below.
                    </li>
                </ul>
            </p>

            <p>
                <h3>
                    Dont have data currently ?, but want to play around !!
                </h3>

                <p>
                    We got you covered, download the sample data and upload it.
                </p>
            </p>
        </div>
    </div>

        
    <div id="below" class="container-fluid bg-dark bg-gradient" style="min-height: 100vh;">
        <br> <br> <br>
        <div class="container text-white">

            <h3>
                Background
            </h3>

            <p>
                In Medical Assitant systems people are opten skeptical of false positives. Thus the general confidence in them is quite low. 
                To combat this issue I have considered 5 modalities to predict stress. Furthermore, depending on the smart watch the owner posseses,
                he may have acess to a portion of the modalities. Thus, this system is fairly general. If a user gets high stress values across 
                various modalities. It is a sign of consern. 
                
                <br>

                The 5 modalalities are visible on the navbar. Research have proven each of them are closely related to stress. For details on the neural 
                network architecture and training protocol please visit the Readme section of this <a href="https://github.com/sa-y-an/retro/blob/main/train_dir/README.md" >repo</a>. 
                The model is trained on the WESAD Dataset. 

                <br>

                The dataset provides many more modalities like heart beat which will be added later

            </p>

            <h3>
                Preprocessing
            </h3>
            
            <p>
                The analog WESAD data is sampled at 700Hz, which implies for 1 second we have 700 sample points. I have considered 
                time sequences consisting of a continuous chunk of 1024 samples while training ie this model will give a prediction 
                every 1.4 seconds (1024/700). Since different subjects have different responses on the signal values,I have used min-max normalisation.
                Furthermore, I have standarized each sequence by z-normalization to ensure uniform scale.  <br/>
                However, while using this site <b> no Preprocessing is required  </b>as I have setup the Preprocessing pipelines accordingly.
            </p>

            <h3 id="instructions">
                Instructions To Use the site
            </h3>

            <p>
                To find out your stress level just input signal from anyone of the modalalities available on the navbar sampled at 700Hz 
                and has a minimum length of 1024 samples. And you will get your stress level.
                <br>
                <U>Conditions</U>
                <ul>
                    <li>
                        upload a .csv file or .txt file consisting of your signal data.
                    </li>
                    <li>
                        If you are using .txt make sure the values are tab or space separated.
                    </li>
                    <li>
                        The signal should be sampled at 700Hz.
                    </li>
                </ul>
            </p>


            Download Sample EDA Data
            <a href="https://drive.google.com/file/d/17RzbfZ568KUnCKQM7yAxdhvp1sLDu41y/view?usp=sharing">
                <button class="btn btn-secondary">
                    .CSV File
                </button>
            </a>
            <a href="https://drive.google.com/file/d/1DJVm5t89rlcBXcakce3r0Y5wP4KLsQzI/view?usp=sharing">
                <button class="btn btn-secondary">
                    .TXT File
                </button>
            </a>


        </div>
    </div>
        
 



{% endblock %}

templates/home/resp.html
{% extends 'base.html' %}{% load static %} 


{% block content %}

<div class="container">

    <div class="main-head">
        Respiration Data 
    </div>

    <br/>


    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
    
                <input type="file" name="myfile" class="btn btn-secondary" />
                <input type="submit" name="submit" value="Upload"  class="btn btn-secondary"/>
    
            </div>
        </form>

    </div>
    

    {% if score %}
        <div class="sub-head">
            Yout last Submission {{path }} was sucessfull
        </div>
           
       
        Here are the results ,  out of {{time}} of data, you were in 
 

        <table class="table table-dark table-striped">
            
            <thead>
                <tr>
                  <th scope="col">Excitation Type</th>
                  <th scope="col"> time (secs )</th>
                  
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">{{ class }}</th>
                  <td>{{ score }}</td>
                </tr>
                </tbody> 
        </table>


    {% else %}

        <p>
            Input the Files
        </p>

    {% endif %}

    <div class="container">

        <h4>
            Please read the "Measure Your Stress Level from this website" section in the home page before for clarity.
        </h4>
        <h3 id="instructions">
            Instructions To Use the site
        </h3>


        <hr>
        
        <p>
            To find out your stress level just input signal from anyone of the modalalities available on the navbar sampled at 700Hz 
            and has a minimum length of 1024 samples. And you will get your stress level.
            <br>
            <U>Conditions</U>
            <ul>
                <li>
                    upload a .csv file or .txt file consisting of your signal data.
                </li>
                <li>
                    If you are using .txt make sure the values are tab or space separated.
                </li>
                <li>
                    The signal should be sampled at 700Hz.
                </li>
            </ul>
        </p>


        <h5>
            Download Sample EDA Data
        </h5>
        <br>
        <a href="https://drive.google.com/file/d/17RzbfZ568KUnCKQM7yAxdhvp1sLDu41y/view?usp=sharing">
            <button class="btn btn-secondary">
                .CSV File
            </button>
        </a>
        
        <a href="https://drive.google.com/file/d/1DJVm5t89rlcBXcakce3r0Y5wP4KLsQzI/view?usp=sharing">
            <button class="btn btn-secondary">
                .TXT File
            </button>
        </a>
    </div>
    
</div>

{% endblock %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:home' %}" style="padding-left: 5px;">Stress Detector</a>


      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">

            
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:ecg' %}">ECG</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:eda' %}">EDA</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:emg' %}">EMG</a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:resp' %}">Resp</a>
          </li>
      
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:temp' %}">Temp</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:about' %}">About</a>
          </li>

        </ul>
        
      </div>
    </div>
  </nav>